# Generated by Django 4.1.2 on 2022-12-07 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=20)),
                ('Cargo', models.CharField(max_length=8)),
                ('Diastrabajados', models.IntegerField()),
                ('Mespagado', models.IntegerField()),
                ('TotalSalario', models.IntegerField()),
            ],
        ),
    ]
