# Generated by Django 4.1.2 on 2022-12-07 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examen', '0002_alter_empleado_mespagado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='TotalSalario',
            field=models.IntegerField(null=True),
        ),
    ]
