# Generated by Django 4.1.2 on 2022-12-07 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examen', '0003_alter_empleado_totalsalario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='Mespagado',
            field=models.CharField(max_length=12),
        ),
    ]
